repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.0
    hooks:
        - id: go-fmt
        - id: go-imports
        - id: no-go-testing
        - id: golangci-lint
        - id: go-unit-tests
  - repo: local
    hooks:
      - id: precommit-message-generate
        name: precommit-message-generate
        entry: commit_message.sh
        language: script
        pass_filenames: false
